Add FallbackPattern in #jv1
codecrafters-io/shell-tester pull request #88
Opened 2024-12-31 07:36 UTC by andy1li

Context:

https://codecrafters-io.slack.com/archives/C032VLSBFM0/p1735502033420399

2025-01-03 10:00 UTC, rohitpaulk commented
I don't think this right - we pass in `cat` as the command, and that's what the program should receive as ARGV[0]. @ryan-gang do you think we can verify this in earlier stages somehow? Maybe in the executable program stage?

2025-01-03 10:11 UTC, rohitpaulk commented
From Slack: 

> We should verify this in #IP1 (Run a program) instead — the first arg passed to a command must be the command the user specified, not the resolved path
> 
> For the existing users who ran into this, we can tell them that when using Command.new they can just use the user input instead of the found path

2025-01-03 10:11 UTC, rohitpaulk requested changes
Note added

2025-01-06 04:57 UTC, ryan-gang commented
Yes, we could add an error scenario to the `run a program` stage, where we print the argv[0] within the error message and assert it normally. 
Something like this: 
```
if (argc < 2) {
    printf("%s: Expected exactly one command line argument, got 0\n", argv[0]);
}
```

But for this to work, we would need to update how we create the custom executable, right now it's just a hardcoded ELF file, where we update a few bytes. 
To support this, we might have to write this in go too.

2025-01-06 05:46 UTC, ryan-gang commented
@rohitpaulk I've opened a [PR](https://github.com/codecrafters-io/shell-tester/pull/92) that updates `custom_executable` to include the invocation command in error messages. 
This adds an early failure scenario when users invoke programs with their full path.
Example: 
<img width="994" alt="image" src="https://github.com/user-attachments/assets/b34928b0-fdf9-4209-ad09-89321d0c7ef8" />

2025-01-06 06:25 UTC, andy1li commented
Superseded by https://github.com/codecrafters-io/shell-tester/pull/92

2025-01-06 06:25 UTC, closed without merging